# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 笑谱

on:
  workflow_dispatch:
  schedule:
    - cron: '55 8-22 * * *' # UTC时间 +8 北京
  watch:
    types: started
  repository_dispatch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【笑谱视频】'
        run: |
          node workflow/xiaopu.js
        env:
          TZ: Asia/shanghai
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
          XP_iboxpayvideoHEADER: ${{ secrets. XP_iboxpayvideoHEADER }}
          XP_iboxpayvideoBODY: ${{ secrets. XP_iboxpayvideoBODY }}
          XP_CASH: ${{ secrets.XP_CASH }}
          XP_live: ${{ secrets.XP_live }}
